[project]
name = "py_app"
version = "0.1.0"
description = "FastAPI in Docker"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pymysql"
]

[build-system]
requires = ["uv"]
build-backend = "uv.build"
